sylius_fixtures:
    suites:
        default:
            fixtures:
                supplier:
                    options:
                        random: 5
        training:
            listeners:
                orm_purger: ~

            fixtures:
                locale:
                    options:
                        locales:
                            - 'en_US'
                            - 'fr_FR'
                            - 'es_ES'
                currency:
                    options:
                        currencies:
                            - 'EUR'
                            - 'USD'

                geographical:
                    options:
                        countries:
                            - 'US'
                            - 'FR'
                            - 'ES'
                        zones:
                            US:
                                name: 'United States of America'
                                countries:
                                    - 'US'
                            WORLD:
                                name: 'World'
                                countries:
                                    - 'US'
                                    - 'FR'
                                    - 'ES'

                channel:
                    options:
                        custom:
                            fashion_web_store:
                                name: 'Common Training Store'
                                code: 'COMMON_CHANNEL'
                                locales:
                                    - '%locale%'
                                currencies:
                                    - 'USD'
                                enabled: true
                                hostname: '%env(resolve:SYLIUS_FIXTURES_HOSTNAME)%'
                                shop_billing_data:
                                    company: 'Sylius'
                                    tax_id: '0001112222'
                                    country_code: 'US'
                                    street: 'Test St. 15'
                                    city: 'eCommerce Town'
                                    postcode: '00 33 22'

                payment_method:
                    options:
                        custom:
                            cash_on_delivery:
                                code: 'cash_on_delivery'
                                name: 'Cash on delivery'
                                channels:
                                    - 'COMMON_CHANNEL'
                            bank_transfer:
                                code: 'bank_transfer'
                                name: 'Bank transfer'
                                channels:
                                    - 'COMMON_CHANNEL'
                                enabled: true

                shipping_method:
                    options:
                        custom:
                            ups:
                                code: 'ups'
                                name: 'UPS'
                                enabled: true
                                channels:
                                    - 'COMMON_CHANNEL'
                            dhl_express:
                                code: 'dhl_express'
                                name: 'DHL Express'
                                channels:
                                    - 'COMMON_CHANNEL'
                            fedex:
                                code: 'fedex'
                                name: 'FedEx'
                                channels:
                                    - 'COMMON_CHANNEL'

                shop_user:
                    name: 'shop_user'
                    options:
                        random: 20
                        custom:
                            -   email: 'shop@example.com'
                                first_name: 'John'
                                last_name: 'Doe'
                                password: 'sylius'

                admin_user:
                    name: 'admin_user'
                    options:
                        custom:
                            -   email: 'sylius@example.com'
                                username: 'sylius'
                                password: 'sylius'
                                enabled: true
                                locale_code: '%locale%'
                                first_name: 'John'
                                last_name: 'Doe'
                                avatar: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/john.jpg'

                            -   email: 'api@example.com'
                                username: 'api'
                                password: 'sylius-api'
                                enabled: true
                                locale_code: '%locale%'
                                first_name: 'Luke'
                                last_name: 'Brushwood'
                                api: true
                                avatar: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/luke.jpg'
