winzou_state_machine:
    app_supplier:
        class: '%app.model.supplier.class%'
        property_path: 'status'
        graph: 'app_supplier'
        state_machine_class: '%sylius.state_machine.class%'
        states:
            new: ~
            trusted: ~
        transitions:
            trust:
                from: [new, trusted]
                to: trusted
        callbacks:
            after:
                send_trust_email:
                    on: ['trust']
                    do: ['@App\Sender\TrustedSupplierEmailSender', 'send']
                    args: ['object']
    sylius_order_checkout:
        transitions:
            address_and_select_shipment:
                from: [cart, addressed, shipping_selected, shipping_skipped, payment_selected, payment_skipped]
                to: shipping_selected
