sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_supplier_admin:
    resource: |
        alias: app.supplier
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: app_supplier
    type: sylius.resource
    prefix: /admin

app_admin_supplier_trust:
    path: /admin/suppliers/{id}/trust
    methods: [PATCH, PUT]
    defaults:
        _controller: app.controller.supplier::applyStateMachineTransitionAction
        _sylius:
            event: trust
            section: admin
            redirect: referer
            state_machine:
                graph: app_supplier
                transition: trust
